name: Python

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    defaults:
      run:
        working-directory: python
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        lfs: true
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
        cache: 'pip'
        cache-dependency-path: 'python/setup.py'
    - name: Build manylinux wheels
      run:
        ./tools/build_wheels.sh
    - name: Pip install
      run: |
        python -m pip install wheels/pylance-0.0.1-cp310-cp310*.whl
        python setup.py develop
    - name: Run python tests
      run: |
        pytest -x -v --durations=10
  mac-build:
    runs-on: macos-12
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Test Pip install
      working-directory: python
      run: |
        python -m pip install -q wheel numpy pyarrow cython
        python setup.py bdist_wheel
        python -m pip install $(ls dist/rikai*.whl)
